### PR TITLE
Part2

### PR DESCRIPTION
**Pull request by rebecca50320**
陳丘舫
http://52.6.218.123:8000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your server.

**Comment by rebecca50320** [comment]
Reloaded

**Review by cwpeng — CHANGES_REQUESTED** [review]
- You should set protection rule on `main` branch
- Content in navigation bar, welcome section, and attraction list should align to left/right with each other.
- Scrollbar of MRT name list should be hidden.
- Layout width exceeds screen width in middle size of devices.

**Comment by rebecca50320** [comment]
Modified.
截圖 2024-06-18 晚上9 31 50

**Review by cwpeng — CHANGES_REQUESTED** [review]
You should test the conditions on 1200px<screen width<1920px.
Screenshot 2024-06-19 094001

**Comment by rebecca50320** [comment]
Modified max-width and width on .m-listbar
截圖 2024-06-19 上午10 55 17

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
