### PR TITLE
Part_1

### PR DESCRIPTION
**Pull request by rebecca50320**
陳丘舫
http://52.6.218.123:8000/api/attractions?page=1
http://52.6.218.123:8000/api/attractions?page=0&keyword=劍潭
http://52.6.218.123:8000/api/attractions?page=0&keyword=北
http://52.6.218.123:8000/api/attraction/10
http://52.6.218.123:8000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your server.

**Comment by rebecca50320** [comment]
reload server. Please try again

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should not get all attraction data from database and do pagination by our own code.(how about 1,000,000 rows). We should use SQL Limit feature to do pagination directly.

**Comment by rebecca50320** [comment]
modified.

**Review by cwpeng — CHANGES_REQUESTED** [review]
images field should be an array containing image URLs for each attraction, not a string.

**Comment by rebecca50320** [comment]
modified on 6/10 14:00

**Comment by rebecca50320** [comment]
modified on 6/10 14:03

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
